- hosts: ansible_host # Ansible VM에서 진행
  gather_facts: no

  tasks:
    - name: Login to Docker Hub
      docker_login:
        # docker hub의 ID
        username: smdfur2000
        # docker hub 토큰은 Jenkins에서 변수처리해서 진행
        password: "{{ lookup('env', 'TOKEN') }}"
        # 재인증이 가능 하도록 설정
        reauthorize: yes

    - name: Build and Push Image # 이미지 빌드 및 docker hub에 푸쉬
      docker_image:
        build:
          path: /home/vagrant/java-hello-world
        name: smdfur2000/java-hello-world
        push: yes
        source: build