- name: Docker Image Build and push
  hosts: ansible_host
  gather_facts: false

  tasks:
    - command: docker image build -t smdfur2000/java-hello-world java-hello-world/
    - command: docker login -u smdfur2000 -p '{{ lookup( "env", "PASS" ) }}'
    - command: docker push smdfur2000/java-hello-world
    - command: docker logout

- name: Docker Run
  hosts: docker_host 
  gather_facts: false

  tasks:
    - command: docker container rm -f java-hello-world 
      ignore_errors: yes 
    - command: docker container run -d -p 8080:8080 --name java-hello-world smdfur2000/java-hello-world